version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing Terraform"
      - wget https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip
      - unzip terraform_1.8.5_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - rm terraform_1.8.5_linux_amd64.zip
  pre_build:
    commands:
      - echo "Configuring AWS credentials"
      - aws sts get-caller-identity
  build:
    commands:
      - echo "Initializing Terraform"
      - terraform init
      - echo "Planning Terraform"
      - terraform validate
      - terraform plan -out=tfplan
  post_build:
    commands:
      - echo "Applying Terraform"
      - terraform apply -input=false tfplan
      - echo "Printing Terraform plan for debugging purposes"
      - terraform show tfplan
      - aws s3 cp tfplan s3://codepipeline-eu-north-1-805195752839/tfplan
      - echo "Terraform applied successfully"
      - terraform destroy -auto-approve
artifacts:
  files:
    - '**/*'
    - 'tfplan'
cache:
  paths:
    - '.terraform/**/*'
